apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: api-slo
  namespace: demo

spec:
  groups:
  - name: api.rules

    rules:

    - alert: ApiErrorRateHigh

      expr: |
        (
          100 *
          sum(rate(flask_http_request_total{status=~"5.."}[5m]))
          /
          sum(rate(flask_http_request_total[5m]))
        ) > 5

      for: 2m

      labels:
        severity: warning

      annotations:
        summary: API error rate too high
        description: Error rate has exceeded 5%